import pygame

# SCREEN CONFIGURATION
SCREEN_WIDTH = 700
SCREEN_HEIGHT = 700
ROWS, COLUMNS = 9, 9
TILE_SIZE = SCREEN_WIDTH//COLUMNS

# COLOUR
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# BOARD COLOUR
NORMAL_TILE = WHITE
CHIT_CARD_SECTION = BLACK

# TILE IMAGE SIZE
IMAGE_SIZE = (SCREEN_WIDTH//COLUMNS - 2, SCREEN_WIDTH//COLUMNS - 2)


