# SCREEN CONFIGURATION
SCREEN_WIDTH = 700
SCREEN_HEIGHT = 700

# BOARD CONFIGURATION
ROWS, COLUMNS = 9, 9
IMAGE_TILE_SIZE = SCREEN_WIDTH//COLUMNS
CENTER_ROW = ROWS // 2
CENTER_COL = COLUMNS // 2

# COLOUR
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
YELLOW = (235, 219, 52)

# IMAGE
IMAGE_SIZE = (SCREEN_WIDTH//COLUMNS - 2, SCREEN_WIDTH//COLUMNS - 2)


